### ISSUE TITLE
 print "%s is nor latin-1 nor utf-8." % files[i] in python 3.4 on Django 1.8

### ISSUE THREAD

**Issue by macolo** [aljosa/django-tinymce#122]
The error also occurs without django_debug_toolbar. It seems the whole compressor thing is a bit broken in python3. It works fine however with the compressor deactivated in settings.py

```
Traceback (most recent call last):
  File "/Users/mario/Webrepublic/projects/ep2/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/mario/.virtualenvs/ep2/lib/python3.4/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/mario/.virtualenvs/ep2/lib/python3.4/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/Users/mario/.virtualenvs/ep2/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/mario/.virtualenvs/ep2/lib/python3.4/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/Users/mario/.virtualenvs/ep2/lib/python3.4/site-packages/debug_toolbar/apps.py", line 15, in ready
    dt_settings.patch_all()
  File "/Users/mario/.virtualenvs/ep2/lib/python3.4/site-packages/debug_toolbar/settings.py", line 232, in patch_all
    patch_root_urlconf()
  File "/Users/mario/.virtualenvs/ep2/lib/python3.4/site-packages/debug_toolbar/settings.py", line 220, in patch_root_urlconf
    reverse('djdt:render_panel')
  File "/Users/mario/.virtualenvs/ep2/lib/python3.4/site-packages/django/core/urlresolvers.py", line 550, in reverse
    app_list = resolver.app_dict[ns]
  File "/Users/mario/.virtualenvs/ep2/lib/python3.4/site-packages/django/core/urlresolvers.py", line 352, in app_dict
    self._populate()
  File "/Users/mario/.virtualenvs/ep2/lib/python3.4/site-packages/django/core/urlresolvers.py", line 308, in _populate
    for name in pattern.reverse_dict:
  File "/Users/mario/.virtualenvs/ep2/lib/python3.4/site-packages/django/core/urlresolvers.py", line 338, in reverse_dict
    self._populate()
  File "/Users/mario/.virtualenvs/ep2/lib/python3.4/site-packages/django/core/urlresolvers.py", line 326, in _populate
    lookups.appendlist(pattern.callback, (bits, p_pattern, pattern.default_args))
  File "/Users/mario/.virtualenvs/ep2/lib/python3.4/site-packages/django/core/urlresolvers.py", line 247, in callback
    self._callback = get_callable(self._callback_str)
  File "/Users/mario/.virtualenvs/ep2/lib/python3.4/functools.py", line 448, in wrapper
    result = user_function(*args, **kwds)
  File "/Users/mario/.virtualenvs/ep2/lib/python3.4/site-packages/django/core/urlresolvers.py", line 106, in get_callable
    mod = import_module(mod_name)
  File "/Users/mario/.virtualenvs/ep2/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/Users/mario/.virtualenvs/ep2/lib/python3.4/site-packages/tinymce/views.py", line 10, in <module>
    from tinymce.compressor import gzip_compressor
  File "/Users/mario/.virtualenvs/ep2/lib/python3.4/site-packages/tinymce/compressor.py", line 133
    print "%s is nor latin-1 nor utf-8." % files[i]
                                       ^
SyntaxError: Missing parentheses in call to 'print'
```

**Comment by Natim** [comment]
If you could file a PR it would be much appreciated otherwise I will fix it
on Monday

**Comment by macolo** [comment]
hmm it looks fixed in your master version. Only you did not include it in your 2.0.1 release.

Apologies, it looks fine - maybe it would make sense to do a quick 2.0.2 release to establish python3 compatibility?

**Comment by Natim** [comment]
Yes sure thanks

**Comment by Natim** [comment]
Done: https://pypi.python.org/pypi/django-tinymce/2.0.2

**Comment by macolo** [comment]
Many thanks!

On Sun, Jul 26, 2015 at 8:59 PM, Rémy HUBSCHER <notifications@github.com>
wrote:

> Done: https://pypi.python.org/pypi/django-tinymce/2.0.2
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aljosa/django-tinymce/issues/122#issuecomment-125027815>
> .
>



-- 
Mario Colombo
Senior Product Specialist

Webrepublic AG
Phone: +41 44 542 90 68 <+41445429068>
Mobile: +41 78 941 73 34 <+41789417334>

mario.colombo@webrepublic.com
