### ISSUE TITLE
Fail to build prior django 1.11

### ISSUE THREAD

**Issue by ad-m** [aljosa/django-tinymce#211]
Hello,

Django-tinymce breaks build prior django 1.11.

Here is example build: https://travis-ci.org/watchdogpolska/watchdog-kj-kultura/builds/218557916

Here is example stacktrace:
```
Traceback (most recent call last):

  File "/home/travis/virtualenv/python3.5.2/bin/py.test", line 11, in <module>

    sys.exit(main())

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/_pytest/config.py", line 47, in main

    config = _prepareconfig(args, plugins)

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/_pytest/config.py", line 156, in _prepareconfig

    pluginmanager=pluginmanager, args=args)

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__

    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec

    return self._inner_hookexec(hook, methods, kwargs)

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>

    _MultiCall(methods, kwargs, hook.spec_opts).execute()

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute

    return _wrapped_call(hook_impl.function(*args), self.execute)

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 250, in _wrapped_call

    wrap_controller.send(call_outcome)

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/_pytest/helpconfig.py", line 32, in pytest_cmdline_parse

    config = outcome.get_result()

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result

    raise ex[1].with_traceback(ex[2])

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__

    self.result = func()

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute

    res = hook_impl.function(*args)

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/_pytest/config.py", line 910, in pytest_cmdline_parse

    self.parse(args)

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/_pytest/config.py", line 1067, in parse

    self._preparse(args, addopts=addopts)

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/_pytest/config.py", line 1038, in _preparse

    args=args, parser=self._parser)

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__

    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec

    return self._inner_hookexec(hook, methods, kwargs)

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>

    _MultiCall(methods, kwargs, hook.spec_opts).execute()

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute

    return _wrapped_call(hook_impl.function(*args), self.execute)

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 254, in _wrapped_call

    return call_outcome.get_result()

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result

    raise ex[1].with_traceback(ex[2])

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__

    self.result = func()

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute

    res = hook_impl.function(*args)

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/pytest_django/plugin.py", line 246, in pytest_load_initial_conftests

    _setup_django()

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/pytest_django/plugin.py", line 149, in _setup_django

    django.setup()

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/__init__.py", line 27, in setup

    apps.populate(settings.INSTALLED_APPS)

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate

    app_config.import_models()

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/apps/config.py", line 202, in import_models

    self.models_module = import_module(models_module_name)

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/importlib/__init__.py", line 126, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 986, in _gcd_import

  File "<frozen importlib._bootstrap>", line 969, in _find_and_load

  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 665, in exec_module

  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed

  File "/home/travis/build/watchdogpolska/watchdog-kj-kultura/watchdog_kj_kultura/main/models.py", line 4, in <module>

    from tinymce.models import HTMLField

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/tinymce/models.py", line 6, in <module>

    from tinymce import widgets as tinymce_widgets

  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/tinymce/widgets.py", line 17, in <module>

    from django.forms.widgets import flatatt

ImportError: cannot import name 'flatatt'
```
``django.forms.widgets.flatatt`` was moved to ``django.forms.utils.flatatt``.

Here is the commit: https://github.com/django/django/commit/b52c73008a9d67e9ddbb841872dc15cdd3d6ee01#diff-f42ac10b4a1091330b3ae0c3d0d0a7cfL10

Greetings,

**Comment by ad-m** [comment]
I am sorry. it was fixed now.
