### ISSUE TITLE
testtinymce fails. Looks like missing staticfiles_settings?

### ISSUE THREAD

**Issue by usernamenumber** [aljosa/django-tinymce#77]
Following the instructions at http://django-tinymce.readthedocs.org/en/latest/installation.html#testing consistently fails for me (Python 2.7.2 on OSX 10.8.5).

Virtualenv setup seems fine:
```
bos-mp9us:tmp brsmith$ mkdir mcetest
bos-mp9us:tmp brsmith$ cd mcetest/
host:mcetest user$ virtualenv --no-site-packages env
New python executable in env/bin/python
Installing Setuptools..............................................................................................................................................................................................................................done.
Installing Pip.....................................................................................................................................................................................................................................................................................................................................done.
host:mcetest user$ . env/bin/activate
(env)host:mcetest user$
```

pip produces some warnings, but everything seems to install OK:
```
(env)host:mcetest user$ pip install Django django-staticfiles django-tinymce
Downloading/unpacking Django
  Downloading Django-1.5.4.tar.gz (8.1MB): 8.1MB downloaded
  Running setup.py egg_info for package Django

    warning: no previously-included files matching '__pycache__' found under directory '*'
    warning: no previously-included files matching '*.py[co]' found under directory '*'
Downloading/unpacking django-staticfiles
  Downloading django-staticfiles-1.2.1.tar.gz (42kB): 42kB downloaded
  Running setup.py egg_info for package django-staticfiles

    warning: no previously-included files matching '*.pyc' found anywhere in distribution
Downloading/unpacking django-tinymce
  Downloading django-tinymce-1.5.1.tar.gz (2.4MB): 2.4MB downloaded
  Running setup.py egg_info for package django-tinymce

    warning: no previously-included files found matching '*.pyc'
Downloading/unpacking django-appconf>=0.4 (from django-staticfiles)
  Downloading django-appconf-0.6.tar.gz
  Running setup.py egg_info for package django-appconf

Downloading/unpacking six (from django-appconf>=0.4->django-staticfiles)
  Downloading six-1.4.1.tar.gz
  Running setup.py egg_info for package six

Installing collected packages: Django, django-staticfiles, django-tinymce, django-appconf, six
  Running setup.py install for Django
    changing mode of build/scripts-2.7/django-admin.py from 644 to 755

    warning: no previously-included files matching '__pycache__' found under directory '*'
    warning: no previously-included files matching '*.py[co]' found under directory '*'
    changing mode of /Users/brsmith/tmp/mcetest/env/bin/django-admin.py to 755
  Running setup.py install for django-staticfiles

    warning: no previously-included files matching '*.pyc' found anywhere in distribution
  Running setup.py install for django-tinymce

    warning: no previously-included files found matching '*.pyc'
  Running setup.py install for django-appconf

  Running setup.py install for six

Successfully installed Django django-staticfiles django-tinymce django-appconf six
Cleaning up...
(env)host:mcetest user$ ls env/lib/python2.7/site-packages/
Django-1.5.4-py2.7.egg-info             pkg_resources.py
_markerlib                              pkg_resources.pyc
appconf                                 setuptools
django                                  setuptools-0.9.8-py2.7.egg-info
django_appconf-0.6-py2.7.egg-info       six-1.4.1-py2.7.egg-info
django_staticfiles-1.2.1-py2.7.egg-info six.py
django_tinymce-1.5.1-py2.7.egg-info     six.pyc
easy_install.py                         staticfiles
easy_install.pyc                        testtinymce
pip                                     tinymce
pip-1.4.1-py2.7.egg-info
(env)host:mcetest user$
```

...but django-admin can't find testtinymce.staticfile_settings:
```
(env)host:mcetest user$ export DJANGO_SETTINGS_MODULE='testtinymce.staticfiles_settings'
(env)host:mcetest user$ django-admin.py syncdb
Traceback (most recent call last):
  File "/Users/brsmith/tmp/mcetest/env/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/Users/brsmith/tmp/mcetest/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 453, in execute_from_command_line
    utility.execute()
  File "/Users/brsmith/tmp/mcetest/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/brsmith/tmp/mcetest/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 263, in fetch_command
    app_name = get_commands()[subcommand]
  File "/Users/brsmith/tmp/mcetest/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 109, in get_commands
    apps = settings.INSTALLED_APPS
  File "/Users/brsmith/tmp/mcetest/env/lib/python2.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/Users/brsmith/tmp/mcetest/env/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/brsmith/tmp/mcetest/env/lib/python2.7/site-packages/django/conf/__init__.py", line 134, in __init__
    raise ImportError("Could not import settings '%s' (Is it on sys.path?): %s" % (self.SETTINGS_MODULE, e))
ImportError: Could not import settings 'testtinymce.staticfiles_settings' (Is it on sys.path?): No module named staticfiles_settings
(env)host:mcetest user$
```

I can't find any evidence of it either:
```
(env)host:mcetest user$ find . -iname '*staticfiles_settings*'
(env)host:mcetest user$ grep -r staticfiles_settings .
(env)host:mcetest user$
```

I haven't used virtualenv before, so if it's not a code problem then perhaps there are some assumptions in the instructions that I'm missing?

**Comment by Natim** [comment]
Should be fixed with current master.
