### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by pericohens** [aljosa/django-tinymce#97]
hello, i have tried install tinymce directly and with pip and I always get the same error .
-------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Perico-Trabajo\codigofacilito\manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line
399, in execute_from_command_line
    utility.execute()
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line
392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 242,
 in run_from_argv
    self.execute(*args, **options.__dict__)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 285,
 in execute
    output = self.handle(*args, **options)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 415,
 in handle
    return self.handle_noargs(**options)
  File "C:\Python27\lib\site-packages\django\core\management\commands\validate.p
y", line 10, in handle_noargs
    self.validate(display_num_errors=True)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 310,
 in validate
    num_errors = get_validation_errors(s, app)
  File "C:\Python27\lib\site-packages\django\core\management\validation.py", lin
e 34, in get_validation_errors
    for (app_name, error) in get_app_errors().items():
  File "C:\Python27\lib\site-packages\django\db\models\loading.py", line 196, in
 get_app_errors
    self._populate()
  File "C:\Python27\lib\site-packages\django\db\models\loading.py", line 75, in
_populate
    self.load_app(app_name, True)
  File "C:\Python27\lib\site-packages\django\db\models\loading.py", line 99, in
load_app
    models = import_module('%s.models' % app_name)
  File "C:\Python27\lib\site-packages\django\utils\importlib.py", line 40, in im
port_module
    __import__(name)
  File "C:\Users\Perico-Trabajo\codigofacilito\blog\models.py", line 3, in <modu
le>
    from tinymce import models as tinymce_models
  File "C:\Python27\lib\site-packages\tinymce\models.py", line 6, in <module>
    from tinymce import widgets as tinymce_widgets
  File "C:\Python27\lib\site-packages\tinymce\widgets.py", line 10, in <module>
    import tinymce.settings
  File "C:\Python27\lib\site-packages\tinymce\settings.py", line 16, in <module>

    JS_ROOT = getattr(settings, 'TINYMCE_JS_ROOT',os.path.join(settings.STATIC_R
OOT, 'tiny_mce'))
  File "C:\Python27\lib\ntpath.py", line 64, in join
    result_drive, result_path = splitdrive(path)
  File "C:\Python27\lib\ntpath.py", line 114, in splitdrive
    if len(p) > 1:
TypeError: object of type 'NoneType' has no len()
---------------------------------------------------------------------------------------------------------------
Does somebody know what is the problem?

**Comment by Natim** [comment]
This was fixed with a362a86 feel free to reopen if you still see an error.
